version: '2'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: infinity-api:latest
    container_name: infinity-api
    ports:
      - "3000:3000"
    env_file:
      - .env
